### ISSUE TITLE
Model predictions on the train set?

### ISSUE THREAD

**Issue by mlplyler** [liamdugan/raid#7]
Thank-you for releasing this dataset!

Is it possible to release the model predictions on the training dataset? We are interested in looking at performance across different splits and it would save a lot of re-compute to have, for example, the binoculars prediction scores across the train set.

thanks!

**Comment by liamdugan** [comment]
Yeah sure thing. I'll get to work on uploading that.

**Comment by liamdugan** [comment]
Ok they're uploaded to the server. You can download them with 
```
$ wget https://dataset.raid-bench.xyz/extra_predictions.zip
$ wget https://dataset.raid-bench.xyz/train_predictions.zip
```

Each zip file has the raw predictions for all of the detectors on that split of the dataset.

**Comment by mlplyler** [comment]
Thanks! Very helpful.
